const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const state={date:new Date(),view:'month',data:{subjects:[],activities:[],school:null},user:null};
const api=async(path,options={})=>{const r=await fetch('/api'+path,{headers:{'Content-Type':'application/json'},...options});if(!r.ok){const e=await r.json().catch(()=>({}));throw Error(e.error||'NÃ£o foi possÃ­vel concluir esta aÃ§Ã£o.')}return r.status===204?null:r.json()};
const pad=n=>String(n).padStart(2,'0'); const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`; const today=()=>iso(new Date());
const dates={week:['Dom','Seg','Ter','Qua','Qui','Sex','SÃ¡b'],months:['Janeiro','Fevereiro','MarÃ§o','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro']};
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function formatDate(v){return new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(v+'T12:00:00')).replace('.','')}
function dueLabel(v){const d=new Date(v+'T12:00:00');const diff=Math.round((d-new Date(today()+'T12:00:00'))/864e5);if(diff<0)return 'ATRASADO';if(diff===0)return 'HOJE';if(diff===1)return 'AMANHÃƒ';return formatDate(v).toUpperCase()}
function typeName(t){return ({dever:'Dever',trabalho:'Trabalho',prova:'Prova',evento:'Evento'})[t]}
function filtered(){const type=$('#typeFilter').value, subject=$('#subjectFilter').value;return state.data.activities.filter(a=>(type==='todos'||a.type===type)&&(subject==='todos'||String(a.subject_id)===subject));}
function render(){renderHeader();renderCalendar();renderDeadlines()}
function renderHeader(){const d=new Date();$('#headerDate').textContent=d.toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}).toUpperCase();$('#displayName').textContent=state.user.username;const s=state.data.school;$('#schoolChip').innerHTML=s?`âŒ‚ <span>${s.name}${s.grade?' Â· '+s.grade:''}</span>`:'âŒ‚ <span>Selecione sua escola</span>'}
function renderCalendar(){const grid=$('#calendarGrid'), agenda=$('#agendaView'); const d=state.date; $('#calendarLabel').textContent=`${dates.months[d.getMonth()]} ${d.getFullYear()}`;
 if(state.view==='month'){grid.hidden=false;agenda.hidden=true;$('.weekdays').hidden=false; const first=new Date(d.getFullYear(),d.getMonth(),1), start=new Date(first);start.setDate(1-first.getDay());let html='';for(let i=0;i<42;i++){const day=new Date(start);day.setDate(start.getDate()+i);const key=iso(day), entries=filtered().filter(a=>a.due_date===key), other=day.getMonth()!==d.getMonth();html+=`<div class="day ${other?'other':''} ${key===today()?'today':''}"><span class="day-number">${day.getDate()}</span>${entries.slice(0,3).map(eventHTML).join('')}${entries.length>3?`<button class="more" data-day="${key}">+${entries.length-3} mais</button>`:''}</div>`}grid.innerHTML=html;
 }else{grid.hidden=true;agenda.hidden=false;$('.weekdays').hidden=true;let start,end;if(state.view==='week'){start=new Date(d);start.setDate(d.getDate()-d.getDay());end=new Date(start);end.setDate(start.getDate()+6)}else{start=end=d}const items=filtered().filter(a=>{const x=new Date(a.due_date+'T12:00:00');return x>=new Date(iso(start)+'T00:00:00')&&x<=new Date(iso(end)+'T23:59:59')});$('#calendarLabel').textContent=state.view==='day'?d.toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'}):`${formatDate(iso(start))} â€” ${formatDate(iso(end))}`;agenda.innerHTML=items.length?items.map(a=>`<div class="agenda-row"><span class="agenda-date">${formatDate(a.due_date)}</span>${eventHTML(a)}<p>${a.subject_name||'Sem matÃ©ria'} ${a.due_time?'Â· '+a.due_time:''}</p></div>`).join(''):'<p class="muted" style="padding:25px;text-align:center">Nenhum compromisso neste perÃ­odo.</p>'}
}
function eventHTML(a){return `<button class="event ${a.type} ${a.status==='concluido'?'concluido':''}" data-event="${a.id}" title="${a.title}">${a.status==='concluido'?'âœ“ ':''}${a.title}</button>`}
function renderDeadlines(){const list=$('#deadlineList');const items=[...state.data.activities].filter(a=>a.status!=='concluido').sort((a,b)=>a.due_date.localeCompare(b.due_date)).slice(0,4);list.innerHTML=items.length?items.map(a=>{const color=a.status==='atrasado'?'#e55f75':a.due_date===today()?'#e55f75':a.due_date===iso(new Date(Date.now()+864e5))?'#ed9d43':'#e0bd39';return `<button class="deadline" data-event="${a.id}"><span class="deadline-dot" style="background:${color}"></span><div><small style="color:${color}">${dueLabel(a.due_date)}</small><h4>${a.title}</h4><p>${a.subject_name||typeName(a.type)}${a.due_time?' Â· '+a.due_time:''}</p></div></button>`}).join(''):'<p class="muted" style="font-size:13px;padding:8px 0 20px">Nenhum prazo prÃ³ximo. Que tal adicionar uma atividade?</p>'}
async function load(){state.data=await api('/bootstrap');populateSubjects();render();if(!state.data.school)$('#schoolModal').showModal()}
function populateSubjects(){const options=state.data.subjects.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');$('#subjectFilter').innerHTML='<option value="todos">Todas as matÃ©rias</option>'+options;$('#subject_id').innerHTML='<option value="">Sem matÃ©ria</option>'+options}
function openActivity(a=null){$('#activityError').textContent='';$('#activityForm').reset();$('#activityId').value=a?.id||'';$('#modalTitle').textContent=a?'Detalhes da atividade':'Adicionar atividade';$('#modalOverline').textContent=a?`${typeName(a.type).toUpperCase()} Â· ${a.status.toUpperCase()}`:'NOVA ATIVIDADE';$('#deleteActivity').hidden=!a;for(const field of ['title','type','subject_id','due_date','due_time','priority','status','description'])if(a&&a[field]!=null)$(`#${field}`).value=a[field];if(!a)$('#due_date').value=iso(state.date);$('#activityModal').showModal()}
async function saveActivity(e){e.preventDefault();const b={};for(const x of ['title','type','subject_id','due_date','due_time','priority','status','description'])b[x]=$('#'+x).value;try{const id=$('#activityId').value;await api(id?'/activities/'+id:'/activities',{method:id?'PUT':'POST',body:JSON.stringify(b)});$('#activityModal').close();toast(id?'Atividade atualizada.':'Atividade adicionada ao calendÃ¡rio.');await load()}catch(e){$('#activityError').textContent=e.message}}
async function initAuth(){const s=await api('/auth/status');if(s.user){state.user=s.user;document.body.classList.toggle('dark',s.user.theme==='dark');$('#authView').hidden=true;$('#app').hidden=false;return load()}const setup=!s.configured;$('#authTitle').textContent=setup?'Crie sua conta':'Entre na sua conta';$('#authSubtitle').textContent=setup?'Sua agenda comeÃ§a por aqui.':'Continue de onde vocÃª parou.';$('#confirmField').hidden=!setup;$('#authButton').innerHTML=setup?'Criar minha agenda <span>â†’</span>':'Entrar <span>â†’</span>';$('#authForm').onsubmit=async e=>{e.preventDefault();try{const p=setup?'/auth/setup':'/auth/login';const b={username:$('#username').value,password:$('#password').value,confirmation:$('#confirmation').value};const r=await api(p,{method:'POST',body:JSON.stringify(b)});state.user=r.user;$('#authView').hidden=true;$('#app').hidden=false;load()}catch(e){$('#authError').textContent=e.message}}}
$('#newActivity').onclick=()=>openActivity();$('#quickAdd').onclick=()=>openActivity();$('#activityForm').onsubmit=saveActivity;$$('[data-close]').forEach(x=>x.onclick=()=>$('#activityModal').close());
document.addEventListener('click',e=>{const target=e.target.closest('[data-event]');if(target)openActivity(state.data.activities.find(a=>a.id===Number(target.dataset.event)));if(e.target.closest('[data-day]')){state.date=new Date(e.target.closest('[data-day]').dataset.day+'T12:00:00');state.view='day';$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view==='day'));renderCalendar()}});
$('#deleteActivity').onclick=async()=>{const id=$('#activityId').value;if(confirm('Excluir esta atividade? Esta aÃ§Ã£o nÃ£o pode ser desfeita.')){await api('/activities/'+id,{method:'DELETE'});$('#activityModal').close();toast('Atividade excluÃ­da.');load()}};
$$('.view').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('.view').forEach(x=>x.classList.toggle('active',x===b));renderCalendar()});
$('#typeFilter').onchange=render;$('#subjectFilter').onchange=render;$('#todayButton').onclick=()=>{state.date=new Date();renderCalendar()};$('#prevDate').onclick=()=>{state.view==='month'?state.date.setMonth(state.date.getMonth()-1):state.date.setDate(state.date.getDate()-(state.view==='week'?7:1));renderCalendar()};$('#nextDate').onclick=()=>{state.view==='month'?state.date.setMonth(state.date.getMonth()+1):state.date.setDate(state.date.getDate()+(state.view==='week'?7:1));renderCalendar()};
$('#viewAll').onclick=()=>{state.view='week';$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.view==='week'));renderCalendar()};$('#themeButton').onclick=async()=>{const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);await api('/theme',{method:'PATCH',body:JSON.stringify({theme:dark?'dark':'light'})});$('#themeButton').innerHTML=`<i>â˜¼</i>${dark?'Modo claro':'Modo escuro'}`};$('#logoutButton').onclick=async()=>{await api('/auth/logout',{method:'POST'});location.reload()};$('#menuButton').onclick=()=>$('.sidebar').classList.toggle('open');
$('#schoolForm').onsubmit=async e=>{e.preventDefault();try{await api('/schools',{method:'POST',body:JSON.stringify({name:$('#schoolName').value,school_year:$('#schoolYear').value,grade:$('#schoolGrade').value,class_name:$('#schoolClass').value,shift:$('#schoolShift').value})});$('#schoolModal').close();toast('Escola cadastrada. Agora adicione suas matÃ©rias.');await load()}catch(e){toast(e.message)}};
initAuth();

